# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-12-15 20:49:24
"""
import arcpy
from arcpy.sa import *

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True
    arcpy.env.scratchWorkspace = arcpy.env.scratchGDB

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("3D")

    DEM_Merged_Clip = arcpy.Raster("DEM_Merged_Clip")
    ImpSurf_ClipProject = arcpy.Raster("ImpSurf_ClipProject")
    Soils_Clip_Proj = "Soils_Clip_Proj"

    # Process: Fill (Fill) (sa)
    Fill_DEM_mb = arcpy.env.scratchGDB + r"\Fill_DEM_mb"
    Fill = Fill_DEM_mb
    Fill_DEM_mb = arcpy.sa.Fill(DEM_Merged_Clip, 0.1)
    Fill_DEM_mb.save(Fill)


    # Process: Flow Direction (Flow Direction) (sa)
    FlowDir_mb = arcpy.env.scratchGDB + r"\FlowDir_mb"
    Flow_Direction = FlowDir_mb
    Output_drop_raster = ""
    with arcpy.EnvManager(cellSize=Fill_DEM_mb, extent="405489.487867412 3429533.80736365 595526.519583412 3651793.06039965 PROJCS[\"NAD_1983_UTM_Zone_12N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-111.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", snapRaster=Fill_DEM_mb):
        FlowDir_mb = arcpy.sa.FlowDirection(Fill_DEM_mb, "NORMAL", Output_drop_raster, "D8")
        FlowDir_mb.save(Flow_Direction)


    # Process: Flow Accumulation (Flow Accumulation) (sa)
    FlowAcc_mb = arcpy.env.scratchGDB + r"\FlowAcc_mb"
    Flow_Accumulation = FlowAcc_mb
    with arcpy.EnvManager(cellSize=Fill_DEM_mb, extent="405489.487867412 3429533.80736365 595526.519583412 3651793.06039965 PROJCS[\"NAD_1983_UTM_Zone_12N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-111.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", snapRaster=Fill_DEM_mb):
        FlowAcc_mb = arcpy.sa.FlowAccumulation(arcpy.Raster(Flow_Direction), "", "FLOAT", "D8")
        FlowAcc_mb.save(Flow_Accumulation)


    # Process: Slope (Slope) (sa)
    Slope_mb = arcpy.env.scratchGDB + r"\Slope_mb"
    Slope = Slope_mb
    with arcpy.EnvManager(cellSize=Fill_DEM_mb, extent="405489.487867412 3429533.80736365 595526.519583412 3651793.06039965 PROJCS[\"NAD_1983_UTM_Zone_12N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-111.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", snapRaster=Fill_DEM_mb):
        Slope_mb = arcpy.sa.Slope(Fill_DEM_mb, "DEGREE", 1, "PLANAR", "METER", "GPU_THEN_CPU")
        Slope_mb.save(Slope)


    # Process: Reclassify (Reclassify) (sa)
    Reclass_Slop_mb = arcpy.env.scratchGDB + r"\Reclass_Slop_mb"
    Reclassify = Reclass_Slop_mb
    with arcpy.EnvManager(cellSize=Fill_DEM_mb, extent="405489.487867412 3429533.80736365 595526.519583412 3651793.06039965 PROJCS[\"NAD_1983_UTM_Zone_12N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-111.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", snapRaster=Fill_DEM_mb):
        Reclass_Slop_mb = arcpy.sa.Reclassify(Slope_mb, "VALUE", "0 5 1;5 10 2;10 15 3;15 25 4;25 90 5", "DATA")
        Reclass_Slop_mb.save(Reclassify)


    # Process: Reclassify (2) (Reclassify) (sa)
    Reclass_Imp_mb = arcpy.env.scratchGDB + r"\Reclass_Imp_mb"
    Reclassify_2_ = Reclass_Imp_mb
    Reclass_Imp_mb = arcpy.sa.Reclassify(ImpSurf_ClipProject, "Value", "0 10 1;10 30 2;30 60 3;60 80 4;80 100 5", "DATA")
    Reclass_Imp_mb.save(Reclassify_2_)


    # Process: Polygon to Raster (Polygon to Raster) (conversion)
    Soils_Polygons_mb = arcpy.env.scratchGDB + r"\Soils_Polygons_mb"
    arcpy.conversion.PolygonToRaster(in_features=Soils_Clip_Proj, value_field="RiskScore", out_rasterdataset=Soils_Polygons_mb, cellsize="9.259259")

    # Process: Reclassify (3) (Reclassify) (sa)
    Reclass_Soil_mb = arcpy.env.scratchGDB + r"\Reclass_Soil_mb"
    Reclassify_3_ = Reclass_Soil_mb
    Reclass_Soil_mb = arcpy.sa.Reclassify(Soils_Polygons_mb, "VALUE", "1 1;2 2;3 3;4 5 5", "DATA")
    Reclass_Soil_mb.save(Reclassify_3_)


    # Process: Weighted Overlay (2) (Weighted Overlay) (sa)
    Weighted_Reclass_mb = arcpy.env.scratchGDB + r"\Weighted_Reclass_mb"
    Weighted_Overlay_2_ = Weighted_Reclass_mb
    Weighted_Reclass_mb = arcpy.sa.WeightedOverlay(WOTable([[Reclass_Slop_mb, 40 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])], [Reclass_Imp_mb, 35 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], ['NODATA', 'NODATA']])], [Reclass_Soil_mb, 25 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [5, 5], ['NODATA', 'NODATA']])]], [1, 9, 1]))
    Weighted_Reclass_mb.save(Weighted_Overlay_2_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=arcpy.env.scratchGDB, workspace=arcpy.env.scratchGDB):
        Model()
